//// Cross-reference parity tests against recharts JS test vectors.
////
//// Validates that weft_chart produces identical outputs to recharts for
//// every input/output pair from scripts/test-vectors.json (generated by
//// recharts-scale v0.4.5). This is the final validation gate ensuring
//// numeric parity with recharts.

import gleam/float
import startest.{describe, it}
import startest/expect
import weft_chart/scale

pub fn parity_tests() {
  describe("recharts parity (test-vectors.json)", [
    tick_parity_tests(),
    fixed_domain_tick_parity_tests(),
    domain_parity_tests(),
  ])
}

// ---------------------------------------------------------------------------
// Tick vectors: getNiceTickValues
// ---------------------------------------------------------------------------

fn tick_parity_tests() {
  describe("tick_parity", [
    it("basic: [0, 7] count=5 -> [0, 2, 4, 6, 8]", fn() {
      scale.nice_ticks(0.0, 7.0, 5, True)
      |> expect.to_equal(expected: [0.0, 2.0, 4.0, 6.0, 8.0])
    }),
    it("round_numbers: [0, 100] count=5 -> [0, 25, 50, 75, 100]", fn() {
      scale.nice_ticks(0.0, 100.0, 5, True)
      |> expect.to_equal(expected: [0.0, 25.0, 50.0, 75.0, 100.0])
    }),
    it("zero_crossing: [-10, 10] count=5 -> [-10, -5, 0, 5, 10]", fn() {
      scale.nice_ticks(-10.0, 10.0, 5, True)
      |> expect.to_equal(expected: [-10.0, -5.0, 0.0, 5.0, 10.0])
    }),
    it("single_value: [5, 5] count=5 -> [3, 4, 5, 6, 7]", fn() {
      scale.nice_ticks(5.0, 5.0, 5, True)
      |> expect.to_equal(expected: [3.0, 4.0, 5.0, 6.0, 7.0])
    }),
    it("small_decimals: [0, 0.7] count=5 -> [0, 0.2, 0.4, 0.6, 0.8]", fn() {
      let result = scale.nice_ticks(0.0, 0.7, 5, True)
      assert_floats_close(result, [0.0, 0.2, 0.4, 0.6, 0.8], 0.001)
      |> expect.to_be_true
    }),
    it(
      "integer_only: [0, 7] count=5 allowDecimals=false -> [0, 2, 4, 6, 8]",
      fn() {
        scale.nice_ticks(0.0, 7.0, 5, False)
        |> expect.to_equal(expected: [0.0, 2.0, 4.0, 6.0, 8.0])
      },
    ),
    it(
      "large_range: [100, 10000] count=5 -> [0, 2500, 5000, 7500, 10000]",
      fn() {
        scale.nice_ticks(100.0, 10_000.0, 5, True)
        |> expect.to_equal(expected: [0.0, 2500.0, 5000.0, 7500.0, 10_000.0])
      },
    ),
    it("few_ticks: [0, 1] count=3 -> [0, 0.5, 1]", fn() {
      scale.nice_ticks(0.0, 1.0, 3, True)
      |> expect.to_equal(expected: [0.0, 0.5, 1.0])
    }),
    it("zero_domain: [0, 0] count=5 -> [0, 1, 2, 3, 4]", fn() {
      scale.nice_ticks(0.0, 0.0, 5, True)
      |> expect.to_equal(expected: [0.0, 1.0, 2.0, 3.0, 4.0])
    }),
    it("all_negative: [-100, -10] count=5 -> [-100, -75, -50, -25, 0]", fn() {
      scale.nice_ticks(-100.0, -10.0, 5, True)
      |> expect.to_equal(expected: [-100.0, -75.0, -50.0, -25.0, 0.0])
    }),
    it("non_round: [3, 97] count=5 -> [0, 25, 50, 75, 100]", fn() {
      scale.nice_ticks(3.0, 97.0, 5, True)
      |> expect.to_equal(expected: [0.0, 25.0, 50.0, 75.0, 100.0])
    }),
  ])
}

// ---------------------------------------------------------------------------
// Fixed domain tick vectors: getTickValuesFixedDomain
// ---------------------------------------------------------------------------

fn fixed_domain_tick_parity_tests() {
  describe("fixed_domain_tick_parity", [
    it("fixed_basic: [0, 100] count=5 -> [0, 25, 50, 75, 100]", fn() {
      scale.nice_ticks_fixed(0.0, 100.0, 5, True)
      |> expect.to_equal(expected: [0.0, 25.0, 50.0, 75.0, 100.0])
    }),
    it("fixed_zero_crossing: [-50, 50] count=5 -> [-50, -25, 0, 25, 50]", fn() {
      scale.nice_ticks_fixed(-50.0, 50.0, 5, True)
      |> expect.to_equal(expected: [-50.0, -25.0, 0.0, 25.0, 50.0])
    }),
    it(
      "fixed_integer_only: [0, 7] count=5 allowDecimals=false -> [0, 2, 4, 7]",
      fn() {
        scale.nice_ticks_fixed(0.0, 7.0, 5, False)
        |> expect.to_equal(expected: [0.0, 2.0, 4.0, 7.0])
      },
    ),
    it("fixed_mid_range: [10, 90] count=5 -> [10, 30, 50, 70, 90]", fn() {
      scale.nice_ticks_fixed(10.0, 90.0, 5, True)
      |> expect.to_equal(expected: [10.0, 30.0, 50.0, 70.0, 90.0])
    }),
  ])
}

// ---------------------------------------------------------------------------
// Domain vectors: auto_domain edge cases
// ---------------------------------------------------------------------------

fn domain_parity_tests() {
  describe("domain_parity", [
    it("auto_auto: data=[20,100] -> [20, 100]", fn() {
      let #(min, max) = scale.auto_domain([20.0, 100.0])
      min |> expect.to_equal(expected: 20.0)
      max |> expect.to_equal(expected: 100.0)
    }),
    it("single value returns degenerate domain", fn() {
      let #(min, max) = scale.auto_domain([5.0, 5.0, 5.0])
      min |> expect.to_equal(expected: 5.0)
      max |> expect.to_equal(expected: 5.0)
    }),
    it("all zeros returns (0, 1)", fn() {
      let #(min, max) = scale.auto_domain([0.0, 0.0])
      min |> expect.to_equal(expected: 0.0)
      max |> expect.to_equal(expected: 1.0)
    }),
    it("empty list returns (0, 1)", fn() {
      let #(min, max) = scale.auto_domain([])
      min |> expect.to_equal(expected: 0.0)
      max |> expect.to_equal(expected: 1.0)
    }),
    it("auto_domain_from_zero starts at 0", fn() {
      let #(min, _max) = scale.auto_domain_from_zero([20.0, 50.0, 100.0])
      min |> expect.to_equal(expected: 0.0)
    }),
  ])
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Compare two lists of floats within a tolerance.
fn assert_floats_close(
  actual: List(Float),
  expected: List(Float),
  tolerance: Float,
) -> Bool {
  case actual, expected {
    [], [] -> True
    [a, ..rest_a], [e, ..rest_e] ->
      case float.absolute_value(a -. e) <. tolerance {
        True -> assert_floats_close(rest_a, rest_e, tolerance)
        False -> False
      }
    _, _ -> False
  }
}
